# scripts/tuning_manager.py

import copy
import itertools

# This constant defines the base for all experiments generated by this manager.
NEW_BASELINE_OVERRIDES = {
    "m_detector": {
        "map_consistency": {
            "adaptive_epsilon_forward_config": {"dmin": 0.1}
        }
    }
}

def generate_static_experiments(target_count=116):
    """
    Generates a predefined, static list of tuning experiments.
    """
    experiments = []

    # Helper to add experiment if name is unique
    def add_experiment(name, override_dict):
        # Ensure the NEW_BASELINE_OVERRIDES are part of this experiment's overrides
        # Start with a deepcopy of the new baseline
        final_overrides = copy.deepcopy(NEW_BASELINE_OVERRIDES)
        
        # Deeply merge the specific override_dict for this experiment
        # This function needs to handle nested keys properly
        def deep_merge(source, destination):
            for key, value in source.items():
                if isinstance(value, dict):
                    node = destination.setdefault(key, {})
                    deep_merge(value, node)
                else:
                    destination[key] = value
            return destination

        deep_merge(override_dict, final_overrides)
        
        # Check for uniqueness if desired, though for generated names it's usually fine
        experiments.append({"name": name, "overrides": final_overrides})

    # 0. Add the New Baseline Itself
    add_experiment("ref_mccFwdDmin0p1", {}) # Empty override as it's handled by NEW_BASELINE_OVERRIDES logic

    # --- Group 1: Occlusion Determination Epsilon (Base for Adaptive Occ) ---
    # Current in config: 0.1
    # Values to try: 0.07, 0.13 (2 experiments)
    for val in [0.07, 0.13]:
        add_experiment(f"Occ_BaseEps_{str(val).replace('.', 'p')}", 
                       {"m_detector": {"occlusion_determination": {"epsilon_depth": val}}})

    # --- Group 2: Systematic Adaptive Occlusion (`occlusion_determination.adaptive_epsilon_depth_config`) ---
    # Config defaults: dthr: 5.0, kthr: 0.01, dmax: 0.5, dmin: 0.05
    # We'll try 2 values for each, creating 2^4 = 16 experiments
    adap_occ_params = {
        "dthr": [3.0, 7.0],      # vs 5.0
        "kthr": [0.005, 0.015],  # vs 0.01
        "dmax": [0.3, 0.7],      # vs 0.5
        "dmin": [0.03, 0.07]     # vs 0.05
    }
    param_names = list(adap_occ_params.keys())
    for values_combo in itertools.product(*[adap_occ_params[k] for k in param_names]):
        current_adap_occ_override = dict(zip(param_names, values_combo))
        current_adap_occ_override["enabled"] = True # Ensure it's enabled
        name_parts = [f"{k}{str(v).replace('.', 'p')}" for k, v in zip(param_names, values_combo)]
        add_experiment(f"AdapOcc_{'_'.join(name_parts)}", 
                       {"m_detector": {"occlusion_determination": {"adaptive_epsilon_depth_config": current_adap_occ_override}}})
    # Count: 2 (Group 1) + 16 (Group 2) = 18 experiments so far (plus baseline = 19)

    # --- Group 3: Event Test Parameters ---
    # M2 (current 2): [1, 3] (2 exp)
    for val in [1, 3]:
        add_experiment(f"Event_M2_{val}", {"m_detector": {"event_detection_logic": {"test2_parallel_away": {"num_historical_DIs_M2": val}}}})
    # M3 (current 3): [2, 4] (2 exp)
    for val in [2, 4]:
        add_experiment(f"Event_M3_{val}", {"m_detector": {"event_detection_logic": {"test3_parallel_towards": {"num_historical_DIs_M3": val}}}})
    # N (current 10): [7, 13] (2 exp)
    for val in [7, 13]:
        add_experiment(f"Event_N_{val}", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"num_historical_DIs_N": val}}}})
    # M4 (current 4, assuming N=10): [3, 5] (2 exp)
    for val in [3, 5]: # These assume N is still around 10 for M4 to make sense
        add_experiment(f"Event_M4_{val}_N10", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"min_occluding_DIs_M4": val}}}})
    # Count: 19 + 8 = 27 experiments

    # --- Group 4: Map Consistency (General) ---
    # time_window_past_s (current 0.5): [0.25, 0.75] (2 exp)
    for val in [0.25, 0.75]:
        add_experiment(f"MCC_Time_{str(val).replace('.', 'p')}s", {"m_detector": {"map_consistency": {"time_window_past_s": val}}})
    # epsilon_phi_deg (current 0.57): [0.3, 0.8] (2 exp)
    for val in [0.3, 0.8]:
        add_experiment(f"MCC_EpsPhi_{str(val).replace('.', 'p')}", {"m_detector": {"map_consistency": {"epsilon_phi_deg": val}}})
    # epsilon_theta_deg (current 1.72): [1.0, 2.5] (2 exp)
    for val in [1.0, 2.5]:
        add_experiment(f"MCC_EpsTheta_{str(val).replace('.', 'p')}", {"m_detector": {"map_consistency": {"epsilon_theta_deg": val}}})
    # threshold_value_count (current 2): [1, 3] (2 exp)
    for val in [1, 3]:
        add_experiment(f"MCC_ThreshCount_{val}", {"m_detector": {"map_consistency": {"threshold_value_count": val}}})
    # interpolation_enabled (current true): [false] (1 exp)
    add_experiment("MCC_InterpDisabled", {"m_detector": {"map_consistency": {"interpolation_enabled": False}}})
    # interpolation_min_depth_m (current 15.0): [10.0, 20.0] (2 exp)
    for val in [10.0, 20.0]:
        add_experiment(f"MCC_InterpMinD_{str(val).replace('.', 'p')}", {"m_detector": {"map_consistency": {"interpolation_min_depth_m": val}}})
    # interpolation_max_neighbors_to_consider (current 20): [10, 30] (2 exp)
    for val in [10, 30]:
        add_experiment(f"MCC_InterpMaxN_{val}", {"m_detector": {"map_consistency": {"interpolation_max_neighbors_to_consider": val}}})
    # Count: 27 + 2+2+2+2+1+2+2 = 27 + 13 = 40 experiments

    # --- Group 5: Systematic Adaptive MCC Backward (`map_consistency.adaptive_epsilon_backward_config`) ---
    # Config defaults: dthr: 20.0, kthr: 0.03, dmax: 1.0, dmin: 0.05
    adap_mccB_params = {
        "dthr": [15.0, 25.0],     # vs 20.0
        "kthr": [0.015, 0.045],   # vs 0.03
        "dmax": [0.7, 1.3],       # vs 1.0
        "dmin": [0.025, 0.075]    # vs 0.05
    }
    param_names_mccB = list(adap_mccB_params.keys())
    for values_combo_mccB in itertools.product(*[adap_mccB_params[k] for k in param_names_mccB]):
        current_adap_mccB_override = dict(zip(param_names_mccB, values_combo_mccB))
        current_adap_mccB_override["enabled"] = True
        name_parts_mccB = [f"{k}{str(v).replace('.', 'p')}" for k, v in zip(param_names_mccB, values_combo_mccB)]
        add_experiment(f"AdapMCCB_{'_'.join(name_parts_mccB)}", 
                       {"m_detector": {"map_consistency": {"adaptive_epsilon_backward_config": current_adap_mccB_override}}})
    # Count: 40 + 16 = 56 experiments

    # --- Group 6: Systematic Adaptive MCC Forward (dthr, kthr, dmax) ---
    # dmin is fixed at 0.1 by NEW_BASELINE_OVERRIDES
    # Config defaults: dthr: 20.0, kthr: 0.07, dmax: 3.0
    adap_mccF_params = {
        "dthr": [15.0, 25.0],     # vs 20.0
        "kthr": [0.05, 0.09],     # vs 0.07
        "dmax": [2.5, 3.5]        # vs 3.0
    }
    param_names_mccF = list(adap_mccF_params.keys())
    for values_combo_mccF in itertools.product(*[adap_mccF_params[k] for k in param_names_mccF]):
        current_adap_mccF_override = dict(zip(param_names_mccF, values_combo_mccF))
        current_adap_mccF_override["enabled"] = True
        current_adap_mccF_override["dmin"] = 0.1 # Explicitly ensure dmin is set with these other changes
        name_parts_mccF = [f"{k}{str(v).replace('.', 'p')}" for k, v in zip(param_names_mccF, values_combo_mccF)]
        add_experiment(f"AdapMCCF_dmin0p1_{'_'.join(name_parts_mccF)}", 
                       {"m_detector": {"map_consistency": {"adaptive_epsilon_forward_config": current_adap_mccF_override}}})
    # Count: 56 + 2*2*2 = 56 + 8 = 64 experiments

    # --- Group 7: RANSAC Ground Parameters ---
    # xyradius_threshold (current 25.0): [15.0, 35.0] (2 exp)
    for val in [15.0, 35.0]:
        add_experiment(f"RANSAC_XYRad_{str(val).replace('.', 'p')}", {"m_detector": {"ransac_ground_params": {"xyradius_threshold": val}}})
    # num_trials (current 20): [10, 30] (2 exp)
    for val in [10, 30]:
        add_experiment(f"RANSAC_Trials_{val}", {"m_detector": {"ransac_ground_params": {"num_trials": val}}})
    # inlier_threshold (current 0.3): [0.2, 0.4] (2 exp)
    for val in [0.2, 0.4]:
        add_experiment(f"RANSAC_Inlier_{str(val).replace('.', 'p')}", {"m_detector": {"ransac_ground_params": {"inlier_threshold": val}}})
    # ground_threshold (current 0.3): [0.2, 0.4] (2 exp)
    for val in [0.2, 0.4]:
        add_experiment(f"RANSAC_GroundTh_{str(val).replace('.', 'p')}", {"m_detector": {"ransac_ground_params": {"ground_threshold": val}}})
    # Count: 64 + 8 = 72 experiments

    # --- Group 8: Initialization Phase ---
    # num_sweeps_for_initial_map (current 10): [5, 15, 20] (3 exp)
    for val in [5, 15, 20]:
        add_experiment(f"Init_Sweeps_{val}", {"m_detector": {"initialization_phase": {"num_sweeps_for_initial_map": val}}})
    # Count: 72 + 3 = 75 experiments

    # --- Group 9: Occlusion Determination (Pixel/Angular Neighborhoods) ---
    # pixel_neighborhood_h (current 2): [1, 3] (2 exp)
    for val in [1, 3]:
        add_experiment(f"Occ_PixelH_{val}", {"m_detector": {"occlusion_determination": {"pixel_neighborhood_h": val}}})
    # pixel_neighborhood_v (current 1): [0, 2] (2 exp)
    for val in [0, 2]:
        add_experiment(f"Occ_PixelV_{val}", {"m_detector": {"occlusion_determination": {"pixel_neighborhood_v": val}}})
    # angular_neighborhood_h_deg (current 0.29): [0.15, 0.45] (2 exp)
    for val in [0.15, 0.45]:
        add_experiment(f"Occ_AngularH_{str(val).replace('.', 'p')}", {"m_detector": {"occlusion_determination": {"angular_neighborhood_h_deg": val}}})
    # angular_neighborhood_v_deg (current 0.4): [0.2, 0.6] (2 exp)
    for val in [0.2, 0.6]:
        add_experiment(f"Occ_AngularV_{str(val).replace('.', 'p')}", {"m_detector": {"occlusion_determination": {"angular_neighborhood_v_deg": val}}})
    # Count: 75 + 8 = 83 experiments

    # --- Fill up to target_count with more variations or combinations ---
    # We have 116 - 1 (baseline) - 82 (current group experiments) = 33 slots left
    
    # Add more variations to Test4 (Perpendicular Event) as it's complex
    # N (current 10): add 5, 15 (2 more)
    for val in [5, 15]: # N=10 is default, 7 and 13 already added
        add_experiment(f"Event_N_{val}_v2", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"num_historical_DIs_N": val}}}})
    # M4 (current 4, for N=10): add 2, 6 (2 more)
    for val in [2, 6]: 
        add_experiment(f"Event_M4_{val}_N10_v2", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"min_occluding_DIs_M4": val}}}})
    # Count: 83 + 4 = 87

    # Try some combined variations for Test4:
    # N=7 with M4=[2,3,4] (3 exp)
    for m4_val in [2,3,4]:
         add_experiment(f"Event_N7_M4_{m4_val}", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"num_historical_DIs_N": 7, "min_occluding_DIs_M4": m4_val}}}})
    # N=13 with M4=[3,4,5,6] (4 exp)
    for m4_val in [3,4,5,6]:
         add_experiment(f"Event_N13_M4_{m4_val}", {"m_detector": {"event_detection_logic": {"test4_perpendicular": {"num_historical_DIs_N": 13, "min_occluding_DIs_M4": m4_val}}}})
    # Count: 87 + 3 + 4 = 94

    # More variations for MCC static labels (this is a bit manual to define variations)
    # Variation 1: Only OCCLUDED_BY_IMAGE
    add_experiment("MCC_StaticLabels_Strict", {"m_detector": {"map_consistency": {"static_labels_for_map_check": ["OCCLUDED_BY_IMAGE", "PRELABELED_STATIC_GROUND"]}}})
    # Variation 2: Add EMPTY_IN_IMAGE
    add_experiment("MCC_StaticLabels_WithEmpty", {"m_detector": {"map_consistency": {"static_labels_for_map_check": ["OCCLUDED_BY_IMAGE", "UNDETERMINED", "PRELABELED_STATIC_GROUND", "EMPTY_IN_IMAGE"]}}})
    # Count: 94 + 2 = 96

    # More variations for adaptive parameters (single param changes from their block's defaults)
    # Adaptive Occlusion (defaults: dthr: 5.0, kthr: 0.01, dmax: 0.5, dmin: 0.05)
    add_experiment(f"AdapOcc_Single_dthr_4p0", {"m_detector": {"occlusion_determination": {"adaptive_epsilon_depth_config": {"enabled":True, "dthr": 4.0}}}})
    add_experiment(f"AdapOcc_Single_kthr_0p02", {"m_detector": {"occlusion_determination": {"adaptive_epsilon_depth_config": {"enabled":True, "kthr": 0.02}}}})
    add_experiment(f"AdapOcc_Single_dmax_0p4", {"m_detector": {"occlusion_determination": {"adaptive_epsilon_depth_config": {"enabled":True, "dmax": 0.4}}}})
    add_experiment(f"AdapOcc_Single_dmin_0p06", {"m_detector": {"occlusion_determination": {"adaptive_epsilon_depth_config": {"enabled":True, "dmin": 0.06}}}})
    # Count: 96 + 4 = 100

    # Adaptive MCC Backward (defaults: dthr: 20.0, kthr: 0.03, dmax: 1.0, dmin: 0.05)
    add_experiment(f"AdapMCCB_Single_dthr_18p0", {"m_detector": {"map_consistency": {"adaptive_epsilon_backward_config": {"enabled":True, "dthr": 18.0}}}})
    add_experiment(f"AdapMCCB_Single_kthr_0p02", {"m_detector": {"map_consistency": {"adaptive_epsilon_backward_config": {"enabled":True, "kthr": 0.02}}}})
    add_experiment(f"AdapMCCB_Single_dmax_0p8", {"m_detector": {"map_consistency": {"adaptive_epsilon_backward_config": {"enabled":True, "dmax": 0.8}}}})
    add_experiment(f"AdapMCCB_Single_dmin_0p06", {"m_detector": {"map_consistency": {"adaptive_epsilon_backward_config": {"enabled":True, "dmin": 0.06}}}})
    # Count: 100 + 4 = 104

    # Adaptive MCC Forward (dmin fixed at 0.1; defaults: dthr: 20.0, kthr: 0.07, dmax: 3.0)
    add_experiment(f"AdapMCCF_Single_dthr_18p0", {"m_detector": {"map_consistency": {"adaptive_epsilon_forward_config": {"enabled":True, "dmin":0.1, "dthr": 18.0}}}})
    add_experiment(f"AdapMCCF_Single_kthr_0p06", {"m_detector": {"map_consistency": {"adaptive_epsilon_forward_config": {"enabled":True, "dmin":0.1, "kthr": 0.06}}}})
    add_experiment(f"AdapMCCF_Single_dmax_2p8", {"m_detector": {"map_consistency": {"adaptive_epsilon_forward_config": {"enabled":True, "dmin":0.1, "dmax": 2.8}}}})
    # Count: 104 + 3 = 107

    # Fill remaining ~9 slots with more single param variations
    # Example:
    add_experiment(f"Occ_BaseEps_0p085", {"m_detector": {"occlusion_determination": {"epsilon_depth": 0.085}}})
    add_experiment(f"Occ_BaseEps_0p115", {"m_detector": {"occlusion_determination": {"epsilon_depth": 0.115}}})
    add_experiment(f"Event_M2_v2", {"m_detector": {"event_detection_logic": {"test2_parallel_away": {"num_historical_DIs_M2": 2}}}}) # Re-test default M2 with new baseline
    add_experiment(f"Event_M3_v2", {"m_detector": {"event_detection_logic": {"test3_parallel_towards": {"num_historical_DIs_M3": 3}}}}) # Re-test default M3
    add_experiment(f"MCC_Time_0p5s_v2", {"m_detector": {"map_consistency": {"time_window_past_s": 0.5}}}) # Re-test default
    add_experiment(f"MCC_EpsPhi_0p57_v2", {"m_detector": {"map_consistency": {"epsilon_phi_deg": 0.57}}})
    add_experiment(f"MCC_EpsTheta_1p72_v2", {"m_detector": {"map_consistency": {"epsilon_theta_deg": 1.72}}})
    add_experiment(f"RANSAC_Inlier_0p3_v2", {"m_detector": {"ransac_ground_params": {"inlier_threshold": 0.3}}})
    add_experiment(f"Init_Sweeps_10_v2", {"m_detector": {"initialization_phase": {"num_sweeps_for_initial_map": 10}}})
    # Count: 107 + 9 = 116

    print(f"Generated {len(experiments)} tuning configurations.")
    if len(experiments) > target_count:
        print(f"Warning: Generated {len(experiments)}, which is more than target {target_count}. Consider trimming.")
    elif len(experiments) < target_count:
        print(f"Info: Generated {len(experiments)}, which is less than target {target_count}. You can add more variations.")
        
    return experiments[:target_count] # Ensure we don't exceed the target

def get_experiments(mode="static", num_trials=100):
    """
    Main entry point to get a list of experiments.
    This is the function your main script will call.
    """
    if mode == "static":
        return generate_static_experiments()
    elif mode == "optuna":
        # This is where the Optuna integration will go.
        # For now, it's a placeholder.
        raise NotImplementedError("Optuna integration is not yet implemented.")
    else:
        raise ValueError(f"Unknown experiment generation mode: {mode}")