# summarizer_config.yaml
folder_to_scan: './src'
output_summary_file: './repo_summary.txt'
file_extension: '.py'
# excluded_subfolder: './src/visualization' # Optional: path to a folder to exclude. Can be absolute or relative.
                                      # Leave blank or remove line for no exclusion.
# Example of no exclusion:
excluded_subfolder: